### ISSUE TITLE
it would be awesome if Dates were automatically de-serialized

### ISSUE THREAD

**Issue by nickperkinslondon** [STRML/react-localstorage#15]
Part of my state is Dates.
I have date-pickers that need those dates in the state.
When my state is saved and restored, my dates have become strings.

It would be awesome if (somehow) those dates were restored as dates.
( for extra bonus points, also make regexes automatically serialize/deserialize -- I also have one of those in my state )

In the meantime, where should I write code to de-serialize my dates?
Is there a hook?...that is called after (or during) every de-serialize?

**Comment by STRML** [comment]
Would be happy to accept a PR that adds a general hook fn (aka after
getSyncState) for this purpose.

On Mar 30, 2017 8:56 AM, "Nick Perkins" <notifications@github.com> wrote:

Part of my state is Dates.
I have date-pickers that need those dates in the state.
When my state is saved and restored, my dates have become strings.

It would be awesome if (somehow) those dates were restored as dates.
( for extra bonus points, also make regexes automatically
serialize/deserialize -- I also have one of those in my state )

In the meantime, where should I write code to de-serialize my dates?
Is there a hook?...that is called after (or during) every de-serialize?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/STRML/react-localstorage/issues/15>, or mute the thread

**Comment by nickperkinslondon** [comment]
You suggest a hook, but I think it would be better if it just happened automatically.
i.e. If a string matches the date pattern exactly, then make it a date.
( date_pattern = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/ )
I guess you would have to put it in your JSON decoder or something to make it work on deep nested values.

In theory, there is a risk that someone wanted to store a string with this exact pattern, and did not want it to come back as a Date....but either that person is going to be disappointed, or I am...and I say it should work for me.  My case is more common and normal.  As the consumer of this service, I don't even care that state is serialized as JSON -- that's an implementation detail -- I just want to get back the state that I had -- dates should come back as dates.  I know you can't solve all of the JSON problems in the world, but this one would be easy and would go a long way.

For now, I am rolling my own local-storage solution, using this date-pattern thing.

**Comment by STRML** [comment]
I don't agree. I don't like magic, nor slowing down serialization for
everyone to fit one user's usecase, however common it might be.

It's certainly not guaranteed that I can serialize anything to
localstorage. What about classes, functions, immutables, even React
components? That's why a hook is useful.

Nick Perkins wrote:
